-- task_2.sql

USE alx_book_store;

CREATE TABLE IF NOT EXISTS AUTHORS (
  AUTHOR_ID INT PRIMARY KEY,
  AUTHOR_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOKS (
  BOOK_ID INT PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  ISBN VARCHAR(20) UNIQUE,
  AUTHOR_ID INT NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  QUANTITY_AVAILABLE INT,
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  CUSTOMER_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  EMAIL VARCHAR(100) UNIQUE,
  ADDRESS TEXT,
  PHONE_NUMBER VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS ORDERS (
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  ORDER_DATE DATE NOT NULL,
  TOTAL_PRICE DECIMAL(10,2),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
  ORDER_DETAIL_ID INT PRIMARY KEY,
  ORDER_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  QUANTITY_ORDERED INT NOT NULL,
  PRICE_PER_UNIT DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);
